# MAXIMUM NUCLEAR ANTI-CADDY NIXPACKS CONFIG
# EXPLICITLY DISABLE CADDY - FORCE PURE NODE.JS SERVER

# ONLY NODE.JS - NO OTHER PROVIDERS
providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "3000"

# EXPLICITLY DEFINE ALL PHASES TO PREVENT AUTO-DETECTION
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

# EXPLICITLY DISABLE CADDY PHASE BY OVERRIDING IT
[phases.caddy]
nixPkgs = []
cmds = ["echo 'CADDY DISABLED'"]

# FORCE START COMMAND - ABSOLUTE OVERRIDE
[start]
cmd = "npm start"

# DISABLE AUTO-DETECTION OF STATIC FILES
[providers.node]
# Force node provider to NOT add static serving