# ULTIMATE NUCLEAR ANTI-CADDY NIXPACKS CONFIG
# FORCE PURE NODE.JS SERVER - ABSOLUTELY NO CADDY

providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "3000"
# Add your production database URL here - replace with your actual database connection string
# DATABASE_URL = "postgresql://username:password@host:port/database"

# EXPLICITLY OVERRIDE ALL PHASES TO PREVENT AUTO-DETECTION
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

# NUCLEAR OPTION: EXPLICITLY DISABLE CADDY PHASE
[phases.caddy]
nixPkgs = []
cmds = ["echo 'CADDY PHASE DISABLED - USING NODE.JS SERVER ONLY'"]

# ABSOLUTE OVERRIDE OF START COMMAND
[start]
cmd = "npm start"

# DISABLE STATIC FILE DETECTION COMPLETELY
[build]
staticDir = ""